name = "Carter Anderson"
bio = "Full-time lead developer, project manager, and original creator of Bevy. Focused on building out core engine systems, guiding project direction, and managing the community."
github = "cart"
itch-io = "cart"
discord = "cart#2833"
discord-userid = "153249376947535872"
mastodon = "@cart@mastodon.social"
sponsor = "https://github.com/sponsors/cart"
profile-picture = "GitHub"
order = 0
