name = "Rob Swain"
bio = "Wielder of light. Turning data into shiny with massive parallelism."
github = "superdump"
discord = "robswain#0382"
discord-userid = "306495754187440132"
twitter = "swainrob"
mastodon = "@swainrob@mastodon.gamedev.place"
profile-picture = "GitHub"
