name = "James Liu"
bio = "Performance by default. A slow engine is an unused engine. Focused on animation, networking, and general engine performance and UX."
github = "james7132"
discord = "james7132#1567"
discord-userid = "151215593553395721"
sponsor = "https://github.com/sponsors/james7132"
profile-picture = "GitHub"
